# Generated by Django 5.2.4 on 2025-07-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("deadline",)},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ("username",),
                "verbose_name": "worker",
                "verbose_name_plural": "workers",
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="last name"),
        ),
    ]
